# Generated by Django 5.2 on 2025-06-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='height',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='height_feet',
            field=models.IntegerField(blank=True, help_text='Height in feet', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='height_inches',
            field=models.IntegerField(blank=True, help_text='Height in inches (0-11)', null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in pounds (lbs)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Target weight in pounds (lbs)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Muscle mass in pounds (lbs)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in pounds (lbs)', max_digits=5, null=True),
        ),
    ]
